version: '3'
services:
  pico:
    container_name: pico
    image: steingartlab/easi:pico
    ip: 192.168.0.10
    ports:
      - 5001:5001
    volumes:
      - /dev/:/dev/
      - picoscope:/picoscope/
    environment: []
    privileged: true
    tty: true
    stdin_open: true
  pithy:
    container_name: pithy
    image: steingartlab/easi:pithy
    ip: 192.168.0.9
    ports:
      - 8001:8080
      - 8888:8888
      - 8004:8081
    volumes:
      - docker.sock:/var/run/docker.sock
      - code:/pithy/code/
      - history:/pithy/code_stamped/
      - passwd:/pithy/assets/
      - files:/pithy/files/
      - images:/pithy/images/
      - drops:/pithy/drops/
      - /home/lab/acoustics:/pithy/acoustics
    environment: []
    privileged: true
    tty: true
    stdin_open: true
  printer:
    container_name: printer
    image: steingartlab/easi:nodeforwarder
    ip: 192.168.0.21
    ports:
      - 9020:9020
    volumes:
      - /dev/:/dev/
    environment:
      - serial_port=/dev/ttyUSB1
      - internet_port=21
      - baud_rate=115200
    privileged: true
    tty: true
    stdin_open: true
  sfogliatella:
    container_name: sfogliatella
    image: steingartlab/easi:sfogliatella
    ip: 192.168.0.12
    ports:
      - 9696:9696
    volumes:
      - sfogliatella:/sfogliatella/
    environment: []
    privileged: true
    tty: true
    stdin_open: true
volumes:
  - picoscope
  - docker.sock
  - code
  - history
  - passwd
  - files
  - images
  - drops
  - sfogliatella
networks:
  acoustics-network:
    ipam:
      config:
        - subnet: 192.168.0.0/24
